server:
   port: 5566
   
spring:
   profiles: 
      active: native
   application: 
      name: wowo-config-server
   cloud:
      config:
         server:
            native:
               search-locations: classpath:/config
   rabbitmq:
      host: 192.168.99.100
      port: 5672
      username: guest
      password: guest
   
eureka:
   client:
      service-url:
         defaultZone: http://navy:123321@127.0.0.1:6868/eureka/             