spring:
   profiles:
      active: dev-8822

---
server:
   port: 8822
   
spring:
   profiles: dev-8822
   application:
      name: wowo-product-server
   
   # 数据库连接池配置
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/wowo?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useOldAliasMetadataBehavior=true
      username: root
      password: Navy123321,.
   
   http:
      encoding:
         charset: utf-8
         force: true
         enabled: true

   redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 5000
      jedis:
         pool:
            max-active: 8

   resources: # 静态资源路径配置
      static-locations: classpath:/META-INF/resources/,classpath:/static/,classpath:/public/,classpath:/resources/,file:${web.upload-path}
      
   session:
      store-type: redis

web:
   upload-path: D:/ # 文件上传路径配置
              
# mybatis配置
mybatis:
   # mapper映射文件路径
   mapper-locations: mapper/*Mapper.xml
   # 需要启用别名的包路径
   type-aliases-package: com.yc.wowo.product.bean

eureka:
   client:
      service-url:
         defaultZone: http://navy:123321@127.0.0.1:6868/eureka/
         
logging:
   level:
      com.yc.wowo.product.mapper: debug