spring:
   # 数据库连接池配置
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/wowo_order?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useOldAliasMetadataBehavior=true
      username: root
      password: Navy123321,.
   
   http:
      encoding:
         charset: utf-8
         force: true
         enabled: true

   redis:
      database: 0
      host: 192.168.99.100
      port: 6379
      password:
      timeout: 5000
      jedis:
         pool:
            max-active: 8

   resources: # 静态资源路径配置
      static-locations: classpath:/META-INF/resources/,classpath:/static/,classpath:/public/,classpath:/resources/,file:${web.upload-path}
      
   session:
      store-type: redis
      
   rabbitmq:
      host: 192.168.99.100
      port: 5672
      username: guest
      password: guest

web:
   upload-path: D:/
              
# mybatis配置
mybatis:
   # mapper映射文件路径
   mapper-locations: mapper/*Mapper.xml
   # 需要启用别名的包路径
   type-aliases-package: com.yc.wowo.order.bean
         
hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 5000

feign:
   hystrix:
      enabled: true
   client:
      config:
         default:
            connectTimeout: 5000
            readTimeout: 5000
